server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  config:
    import: optional:configserver:http://localhost:8888
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Keycloak Authentication Routes
        - id: keycloak-auth
          uri: ${KEYCLOAK_URL:http://localhost:8080}
          predicates:
            - Path=/auth/**,/realms/**
          filters:
            - StripPrefix=0
        
        # User Service Routes (Keycloak Protected)
        - id: user-service-keycloak
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/rest/users/**
          filters:
            - name: JwtAuthentication
              args:
                keycloak-url: ${KEYCLOAK_URL:http://localhost:8080}
                realm: ${KEYCLOAK_REALM:event-platform}
                client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}
        
        # Task Service Routes (Keycloak Protected)
        - id: task-service-keycloak
          uri: lb://task-service
          predicates:
            - Path=/api/v1/rest/tasks/**
          filters:
            - name: JwtAuthentication
              args:
                keycloak-url: ${KEYCLOAK_URL:http://localhost:8080}
                realm: ${KEYCLOAK_REALM:event-platform}
                client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}
        
        # Notification Service Routes (Keycloak Protected)
        - id: notification-service-keycloak
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: JwtAuthentication
              args:
                keycloak-url: ${KEYCLOAK_URL:http://localhost:8080}
                realm: ${KEYCLOAK_REALM:event-platform}
                client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}
        
        # Public Routes (No Authentication)
        - id: swagger-ui
          uri: lb://user-service
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**
        
        - id: actuator-health
          uri: lb://user-service
          predicates:
            - Path=/actuator/health

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 200
            redis-rate-limiter.requestedTokens: 1
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://127.0.0.1:3000"
              - "${KEYCLOAK_URL:http://localhost:8080}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# Keycloak Configuration
keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:event-platform}
  client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service-keycloak:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      task-service-keycloak:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.eureka: DEBUG
    reactor.netty: DEBUG
    com.home.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{traceId:-},%X{spanId:-}] - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
