server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-rest
          uri: lb://user-service
          predicates:
            - Path=/api/v1/rest/users/**
        - id: task-service-kotlin-rest
          uri: lb://task-service-kotlin
          predicates:
            - Path=/api/v1/rest/tasks/**
