spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_platform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration

logging:
  level:
    com.home: DEBUG
    org.springframework.web: DEBUG
