spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/event_platform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  locations: classpath:db/migration

logging:
  level:
    com.home: INFO
    org.springframework.web: WARN
