server:
  port: 0

spring:
  application:
    name: task-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/taskdb}