/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "super-pet"

include(
    ":apps:api-gateway",
    ":services:config-server",
    ":services:discovery-server",
    ":services:notification-service",
    ":services:task-service",
    ":services:user-service",
    ":shared:schemas"
)
