spring:
  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema.registry.url: http://schema-registry:8081
  
  mail:
    host: mailhog
    port: 1025

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
