apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: super-pet-dev
  labels:
    app: task-service
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
        environment: development
    spec:
      containers:
      - name: task-service
        image: your-docker-registry/super-pet/task-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/taskdb"
        - name: MONGODB_DATABASE
          value: "taskdb"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: EUREKA_URL
          value: "http://discovery-server:8761/eureka/"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: super-pet-dev
  labels:
    app: task-service
spec:
  selector:
    app: task-service
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP
