# Docker среда
spring:
  profiles:
    active: docker
  
  # Docker настройки БД
  datasource:
    url: jdbc:postgresql://postgres:5432/event_platform
    username: postgres
    password: postgres
  
  # MongoDB для Docker
  data:
    mongodb:
      uri: mongodb://mongodb:27017/taskdb

# Docker настройки Kafka
spring:
  kafka:
    bootstrap-servers: kafka:9092

# Docker настройки Eureka
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

# Docker настройки Config Server
spring:
  cloud:
    config:
      uri: http://config-server:8888

# Docker логирование
logging:
  level:
    com.home: INFO
    org.springframework.web: WARN
    org.springframework.kafka: INFO
