# Production среда
spring:
  profiles:
    active: production
  
  # Production настройки БД
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Production MongoDB
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

# Production Kafka
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
    sasl:
      mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      jaas:
        config: ${KAFKA_SASL_JAAS_CONFIG}

# Production Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

# Production Config Server
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}

# Production логирование
logging:
  level:
    com.home: INFO
    org.springframework.web: WARN
    org.springframework.kafka: WARN
  file:
    name: /app/logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

# Production мониторинг
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
