# Task Service - Local Development Configuration
# Использует упрощенные настройки для локальной разработки

# Импорт базовых шаблонов
spring:
  config:
    import:
      - optional:classpath:/templates/base-service.yml
      - optional:classpath:/templates/kafka.yml

# Специфичные настройки для локальной разработки
server:
  port: 8082

spring:
  application:
    name: task-service
  
  # MongoDB для локальной разработки
  data:
    mongodb:
      uri: mongodb://localhost:27017/taskdb_local
      database: taskdb_local
      auto-index-creation: true
  
  # H2 для тестирования (опционально)
  h2:
    console:
      enabled: true
      path: /h2-console

# Отключение некоторых проверок для локальной разработки
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Упрощенное логирование для разработки
logging:
  level:
    com.home.task: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG