server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  kafka:
    topics:
      user:
        created: user.created
        updated: user.updated
        deleted: user.deleted

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
