spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/event_platform
    username: postgres
    password: postgres
  
  kafka:
    bootstrap-servers: kafka:29092
    properties:
      schema.registry.url: http://schema-registry:8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

