spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-org/config-repo.git
          username: dfhh12
          password: glpat-qdnkKtk3PsSiwnscngTr
          clone-on-start: true
          search-paths: .