# Fixed Config Server configuration for local development
spring:
  cloud:
    config:
      server:
        native:
          # Correct path to event-platform-configs
          searchLocations: 
            # Search in service-specific folders
            - file:///${user.home}/dev/super-pet/event-platform-configs/{application}
            # Search in root for common configs
            - file:///${user.home}/dev/super-pet/event-platform-configs/
            # Alternative: relative path (uncomment if needed)
            # - file:../../event-platform-configs/{application}
            # - file:../../event-platform-configs/
          
          # Enable fail fast for debugging
          failOnError: false
          
          # Add version information
          addLabelLocations: false

# Logging for debugging
logging:
  level:
    org.springframework.cloud.config: DEBUG

# Management endpoints for testing
management:
  endpoints:
    web:
      exposure:
        include: "*"
