# Базовые настройки базы данных
spring:
  # PostgreSQL настройки
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/event_platform}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  # JPA настройки
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

  # MongoDB настройки (для task-service)
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/taskdb}
      database: ${MONGODB_DATABASE:taskdb}
      auto-index-creation: true

# Flyway для миграций PostgreSQL
flyway:
  enabled: ${FLYWAY_ENABLED:true}
  locations: classpath:db/migration
  baseline-on-migrate: true
  validate-on-migrate: true
